import { opacitySwitch, intensitySwitch } from "./css-utils";
import { ThemeColorOpacity, ThemeColorFullWithTransparent, ThemeColorIntensity } from "../styles";

export function borderColorCss(color: ThemeColorFullWithTransparent, intensity?: ThemeColorIntensity, opacity?: ThemeColorOpacity) {
  intensity ??= 'DEFAULT';
  opacity ??= 'full';

  switch(color) {
    case 'black':
      return opacitySwitch(opacity,
        intensitySwitch(intensity,
          'border-slate-900',
          'border-slate-400',
          'border-black'),
        intensitySwitch(intensity,
          'border-slate-900/75',
          'border-slate-400/75',
          'border-black/75'),
        intensitySwitch(intensity,
          'border-slate-900/50',
          'border-slate-400/50',
          'border-black/50'),
        intensitySwitch(intensity,
          'border-slate-900/25',
          'border-slate-400/25',
          'border-black/25'),
        intensitySwitch(intensity,
          'border-slate-900/10',
          'border-slate-400/10',
          'border-black/10'));
    case 'white':
      return opacitySwitch(opacity,
        intensitySwitch(intensity,
          'border-white',
          'border-white',
          'border-slate-50'),
        intensitySwitch(intensity,
          'border-white/75',
          'border-white/75',
          'border-slate-50/75'),
        intensitySwitch(intensity,
          'border-white/50',
          'border-white/50',
          'border-slate-50/50'),
        intensitySwitch(intensity,
          'border-white/25',
          'border-white/25',
          'border-slate-50/25'),
        intensitySwitch(intensity,
          'border-white/10',
          'border-white/10',
          'border-slate-50/10'));            
    case 'surface':
      return opacitySwitch(opacity,
        intensitySwitch(intensity,
          'border-hallpass-surface',
          'border-hallpass-surface-light',
          'border-hallpass-surface-dark'),
        intensitySwitch(intensity,
          'border-hallpass-surface/75',
          'border-hallpass-surface-light/75',
          'border-hallpass-surface-dark/75'),
        intensitySwitch(intensity,
          'border-hallpass-surface/50',
          'border-hallpass-surface-light/50',
          'border-hallpass-surface-dark/50'),
        intensitySwitch(intensity,
          'border-hallpass-surface/25',
          'border-hallpass-surface-light/25',
          'border-hallpass-surface-dark/25'),
        intensitySwitch(intensity,
          'border-hallpass-surface/10',
          'border-hallpass-surface-light/10',
          'border-hallpass-surface-dark/10'));
    case 'background':
      return opacitySwitch(opacity,
        intensitySwitch(intensity, 
          'border-hallpass-background',
          'border-hallpass-background/90',
          'border-slate-50'),
        intensitySwitch(intensity, 
          'border-hallpass-background/75',
          'border-hallpass-background/70',
          'border-slate-50/75'),
        intensitySwitch(intensity, 
          'border-hallpass-background/50',
          'border-hallpass-background/40',
          'border-slate-50/50'),
        intensitySwitch(intensity, 
          'border-hallpass-background/25',
          'border-hallpass-background/20',
          'border-slate-50/25'),
        intensitySwitch(intensity, 
          'border-hallpass-background/10',
          'border-hallpass-background/5',
          'border-slate-50/10'),
          );
    case 'transparent':
      return 'border-transparent'
    case 'neutral':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'border-hallpass-neutral',
          'border-hallpass-neutral-light',
          'border-hallpass-neutral-dark'),
        intensitySwitch(intensity,
          'border-hallpass-neutral/75',
          'border-hallpass-neutral-light/75',
          'border-hallpass-neutral-dark/75'),
        intensitySwitch(intensity,
          'border-hallpass-neutral/50',
          'border-hallpass-neutral-light/50',
          'border-hallpass-neutral-dark/50'),
        intensitySwitch(intensity,
          'border-hallpass-neutral/25',
          'border-hallpass-neutral-light/25',
          'border-hallpass-neutral-dark/25'),
        intensitySwitch(intensity,
          'border-hallpass-neutral/10',
          'border-hallpass-neutral-light/10',
          'border-hallpass-neutral-dark/10'));
    case 'primary':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'border-hallpass-primary',
          'border-hallpass-primary-light',
          'border-hallpass-primary-dark'),
        intensitySwitch(intensity,
          'border-hallpass-primary/75',
          'border-hallpass-primary-light/75',
          'border-hallpass-primary-dark/75'),
        intensitySwitch(intensity,
          'border-hallpass-primary/50',
          'border-hallpass-primary-light/50',
          'border-hallpass-primary-dark/50'),
        intensitySwitch(intensity,
          'border-hallpass-primary/25',
          'border-hallpass-primary-light/25',
          'border-hallpass-primary-dark/25'),
        intensitySwitch(intensity,
          'border-hallpass-primary/10',
          'border-hallpass-primary-light/10',
          'border-hallpass-primary-dark/10'));
    case 'secondary':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'border-hallpass-secondary',
          'border-hallpass-secondary-light',
          'border-hallpass-secondary-dark'),
        intensitySwitch(intensity,
          'border-hallpass-secondary/75',
          'border-hallpass-secondary-light/75',
          'border-hallpass-secondary-dark/75'),
        intensitySwitch(intensity,
          'border-hallpass-secondary/50',
          'border-hallpass-secondary-light/50',
          'border-hallpass-secondary-dark/50'),
        intensitySwitch(intensity,
          'border-hallpass-secondary/25',
          'border-hallpass-secondary-light/25',
          'border-hallpass-secondary-dark/25'),
        intensitySwitch(intensity,
          'border-hallpass-secondary/10',
          'border-hallpass-secondary-light/10',
          'border-hallpass-secondary-dark/10'));
    case 'error':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'border-hallpass-error',
          'border-hallpass-error/80',
          'border-hallpass-error'),
        intensitySwitch(intensity,
          'border-hallpass-error/75',
          'border-hallpass-error/70',
          'border-hallpass-error/75'),
        intensitySwitch(intensity,
          'border-hallpass-error/50',
          'border-hallpass-error/40',
          'border-hallpass-error/60'),
        intensitySwitch(intensity,
          'border-hallpass-error/25',
          'border-hallpass-error/20',
          'border-hallpass-error/30'),
        intensitySwitch(intensity,
          'border-hallpass-error/10',
          'border-hallpass-error/2',
          'border-hallpass-error/10'));        
    default:
      throw new Error(`Unsupported background color: ${color}`);
  }
}
