import { opacitySwitch, intensitySwitch } from "./css-utils";
import { ThemeColorBasic, ThemeColorBlackWhite, ThemeColorIntensity, ThemeColorOpacity } from "../styles";

export function textColorCss(color: ThemeColorBasic | ThemeColorBlackWhite, intensity?: ThemeColorIntensity, opacity?: ThemeColorOpacity) {
  intensity ??= 'DEFAULT';
  opacity ??= 'full';


  switch(color) {
    case 'black':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-slate-900 contrast-more:text-black',
          'text-slate-400 contrast-more:text-black',
          'text-black'),
        intensitySwitch(intensity,
          'text-slate-900/75 contrast-more:text-black',
          'text-slate-400/75 contrast-more:text-black',
          'text-black/75'),
        intensitySwitch(intensity,
          'text-slate-900/50 contrast-more:text-black',
          'text-slate-400/50 contrast-more:text-black',
          'text-black/50 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-slate-900/25 contrast-more:text-black',
          'text-slate-400/25 contrast-more:text-black',
          'text-black/25 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-slate-900/10 contrast-more:text-black',
          'text-slate-400/10 contrast-more:text-black',
          'text-black/10 contrast-more:text-black'));
    case 'white':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-white',
          'text-white',
          'text-slate-50'),
        intensitySwitch(intensity,
          'text-white/75',
          'text-white/75',
          'text-slate-50/75'),
        intensitySwitch(intensity,
          'text-white/50',
          'text-white/50',
          'text-slate-50/50'),
        intensitySwitch(intensity,
          'text-white/25',
          'text-white/25',
          'text-slate-50/25'),
        intensitySwitch(intensity,
          'text-white/10',
          'text-white/10',
          'text-slate-50/10'));
    case 'neutral':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-neutral contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-light contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-dark contrast-more:text-hallpass-black'),
        intensitySwitch(intensity,
          'text-hallpass-neutral/75 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral/75-light contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral/75-dark contrast-more:text-hallpass-black'),
        intensitySwitch(intensity,
          'text-hallpass-neutral/50 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-light/50 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-dark/50 contrast-more:text-hallpass-neutral-dark'),
        intensitySwitch(intensity,
          'text-hallpass-neutral/25 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-light/25 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-dark/25 contrast-more:text-hallpass-neutral-dark'),
        intensitySwitch(intensity,
          'text-hallpass-neutral/10 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-light/10 contrast-more:text-hallpass-neutral-dark',
          'text-hallpass-neutral-dark/10 contrast-more:text-hallpass-neutral-dark'));
    case 'primary':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-primary contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-light contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-dark contrast-more:text-hallpass-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-primary/75 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary/75-light contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary/75-dark contrast-more:text-hallpass-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-primary/50 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-light/50 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-dark/50 contrast-more:text-hallpass-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-primary/25 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-light/25 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-dark/25 contrast-more:text-hallpass-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-primary/10 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-light/10 contrast-more:text-hallpass-primary-dark',
          'text-hallpass-primary-dark/10 contrast-more:text-hallpass-primary-dark'));
    case 'secondary':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-secondary contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-light contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-dark contrast-more:text-hallpass-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-secondary/75 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary/75-light contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary/75-dark contrast-more:text-hallpass-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-secondary/50 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-light/50 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-dark/50 contrast-more:text-hallpass-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-secondary/25 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-light/25 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-dark/25 contrast-more:text-hallpass-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-secondary/10 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-light/10 contrast-more:text-hallpass-secondary-dark',
          'text-hallpass-secondary-dark/10 contrast-more:text-hallpass-secondary-dark'));
    case 'error':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-error contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-light contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-dark contrast-more:text-hallpass-red-dark'),
        intensitySwitch(intensity,
          'text-hallpass-error/75 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-light/75 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-dark/75 contrast-more:text-hallpass-red-dark'),
        intensitySwitch(intensity,
          'text-hallpass-error/50 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-light/50 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-dark/50 contrast-more:text-hallpass-red-dark'),
        intensitySwitch(intensity,
          'text-hallpass-error/25 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-light/25 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-dark/25 contrast-more:text-hallpass-red-dark'),
        intensitySwitch(intensity,
          'text-hallpass-error/10 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-light/10 contrast-more:text-hallpass-red-dark',
          'text-hallpass-error-dark/10 contrast-more:text-hallpass-red-dark'));
    default:
      throw new Error(`Unsupported text color: ${color}`);
  }
}
