import { opacitySwitch, intensitySwitch } from "./css-utils";
import { ThemeColorFull, ThemeColorIntensity, ThemeColorOpacity } from "../styles";
import { assertExhaustive } from "../misc";

export function textOnColorCss(color: ThemeColorFull, intensity?: ThemeColorIntensity, opacity?: ThemeColorOpacity) {
  intensity ??= 'DEFAULT';
  opacity ??= 'full';


  switch(color) {
    case 'background':
      return 'text-black';
    case 'white':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-slate-900 contrast-more:text-black',
          'text-slate-400 contrast-more:text-black',
          'text-black'),
        intensitySwitch(intensity,
          'text-slate-900/75 contrast-more:text-black',
          'text-slate-400/75 contrast-more:text-black',
          'text-black/75'),
        intensitySwitch(intensity,
          'text-slate-900/50 contrast-more:text-black',
          'text-slate-400/50 contrast-more:text-black',
          'text-black/50 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-slate-900/25 contrast-more:text-black',
          'text-slate-400/25 contrast-more:text-black',
          'text-black/25 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-slate-900/10 contrast-more:text-black',
          'text-slate-400/10 contrast-more:text-black',
          'text-black/10 contrast-more:text-black'));
    case 'black':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-white',
          'text-white',
          'text-slate-50'),
        intensitySwitch(intensity,
          'text-white/75',
          'text-white/75',
          'text-slate-50/75'),
        intensitySwitch(intensity,
          'text-white/50',
          'text-white/50',
          'text-slate-50/50'),
        intensitySwitch(intensity,
          'text-white/25',
          'text-white/25',
          'text-slate-50/25'),
        intensitySwitch(intensity,
          'text-white/10',
          'text-white/10',
          'text-slate-50/10'));
    case 'neutral':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-on-neutral contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-light contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-dark contrast-more:text-hallpass-black'),
        intensitySwitch(intensity,
          'text-hallpass-on-neutral/75 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral/75-light contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral/75-dark contrast-more:text-hallpass-black'),
        intensitySwitch(intensity,
          'text-hallpass-on-neutral/50 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-light/50 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-dark/50 contrast-more:text-hallpass-on-neutral-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-neutral/25 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-light/25 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-dark/25 contrast-more:text-hallpass-on-neutral-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-neutral/10 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-light/10 contrast-more:text-hallpass-on-neutral-dark',
          'text-hallpass-on-neutral-dark/10 contrast-more:text-hallpass-on-neutral-dark'));
    case 'primary':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-on-primary contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-light contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-dark contrast-more:text-hallpass-on-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-primary/75 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary/75-light contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary/75-dark contrast-more:text-hallpass-on-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-primary/50 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-light/50 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-dark/50 contrast-more:text-hallpass-on-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-primary/25 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-light/25 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-dark/25 contrast-more:text-hallpass-on-primary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-primary/10 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-light/10 contrast-more:text-hallpass-on-primary-dark',
          'text-hallpass-on-primary-dark/10 contrast-more:text-hallpass-on-primary-dark'));
    case 'secondary':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-on-secondary contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-light contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-dark contrast-more:text-hallpass-on-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-secondary/75 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary/75-light contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary/75-dark contrast-more:text-hallpass-on-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-secondary/50 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-light/50 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-dark/50 contrast-more:text-hallpass-on-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-secondary/25 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-light/25 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-dark/25 contrast-more:text-hallpass-on-secondary-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-secondary/10 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-light/10 contrast-more:text-hallpass-on-secondary-dark',
          'text-hallpass-on-secondary-dark/10 contrast-more:text-hallpass-on-secondary-dark'));
    case 'error':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-on-error contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-light contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-dark contrast-more:text-hallpass-on-error-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-error/75 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-light/75 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-dark/75 contrast-more:text-hallpass-on-error-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-error/50 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-light/50 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-dark/50 contrast-more:text-hallpass-on-error-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-error/25 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-light/25 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-dark/25 contrast-more:text-hallpass-on-error-dark'),
        intensitySwitch(intensity,
          'text-hallpass-on-error/10 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-light/10 contrast-more:text-hallpass-on-error-dark',
          'text-hallpass-on-error-dark/10 contrast-more:text-hallpass-on-error-dark'));
    case 'surface':
      return opacitySwitch(opacity, 
        intensitySwitch(intensity,
          'text-hallpass-on-surface contrast-more:text-black',
          'text-hallpass-on-surface-light contrast-more:text-black',
          'text-hallpass-on-surface-dark contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-hallpass-on-surface/75 contrast-more:text-black',
          'text-hallpass-on-surface-light/75 contrast-more:text-black',
          'text-hallpass-on-surface-dark/75 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-hallpass-on-surface/50 contrast-more:text-black',
          'text-hallpass-on-surface-light/50 contrast-more:text-black',
          'text-hallpass-on-surface-dark/50 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-hallpass-on-surface/25 contrast-more:text-black',
          'text-hallpass-on-surface-light/25 contrast-more:text-black',
          'text-hallpass-on-surface-dark/25 contrast-more:text-black'),
        intensitySwitch(intensity,
          'text-hallpass-on-surface/10 contrast-more:text-black',
          'text-hallpass-on-surface-light/10 contrast-more:text-black',
          'text-hallpass-on-surface-dark/10 contrast-more:text-black'));
    default:
      assertExhaustive(color);
  }
}
